/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"fmt"
	"time"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	logf "sigs.k8s.io/controller-runtime/pkg/log"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	secretsv1alpha1 "github.com/mogilyoy/k8s-secret-manager/api/v1alpha1"
)

// SecretClaimReconciler reconciles a SecretClaim object
type SecretClaimReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=secrets.myapp.io,resources=secretclaims,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=secrets.myapp.io,resources=secretclaims/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=secrets.myapp.io,resources=secretclaims/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch;create;update;patch;delete

// Reconcile is part of the main kubernetes reconciliation loop which aims to
// move the current state of the cluster closer to the desired state.
// TODO(user): Modify the Reconcile function to compare the state specified by
// the SecretClaim object against the actual cluster state, and then
// perform operations to make the cluster state reflect the state specified by
// the user.
//
// For more details, check Reconcile and its Result here:
// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.22.4/pkg/reconcile
func (r *SecretClaimReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := logf.FromContext(ctx)

	var claim secretsv1alpha1.SecretClaim
	if err := r.Get(ctx, req.NamespacedName, &claim); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	logger.Info("Reconciling SecretClaim", "name", claim.Name, "type", claim.Spec.Type)

	targetSecretName := claim.Name
	var secret corev1.Secret

	err := r.Get(ctx, client.ObjectKey{
		Name:      targetSecretName,
		Namespace: claim.Namespace,
	}, &secret)

	if err != nil && errors.IsNotFound(err) {
		// Секрета нет -> нужно создать
		logger.Info("Creating new Secret", "name", targetSecretName)

		if err := r.createSecret(ctx, &claim); err != nil {
			logger.Error(err, "Failed to create Secret")
			r.updateStatus(ctx, &claim, false, err.Error())
			return ctrl.Result{}, err
		}

		r.updateStatus(ctx, &claim, true, "")
		return ctrl.Result{}, nil

	} else if err != nil {
		logger.Error(err, "Failed to get Secret")
		return ctrl.Result{RequeueAfter: time.Minute}, err
	}

	if !metav1.IsControlledBy(&secret.ObjectMeta, &claim) {
		logger.Info("Secret exists but is not controlled by SecretClaim")
		return ctrl.Result{}, nil
	}

	if !claim.Status.Synced {
		logger.Info("SecretClaim not synced yet, updating status")
		r.updateStatus(ctx, &claim, true, "")
		return ctrl.Result{}, nil
	}

	needsSecretUpdate := false

	if claim.Spec.Type == "AutoGenerated" {
		if claim.Spec.Generation == nil {
			err := fmt.Errorf("GenerationConfig spec is nil for AutoGenerated claim")
			logger.Error(err, "Invalid generation spec")
			r.updateStatus(ctx, &claim, false, err.Error())
			return ctrl.Result{}, err
		}

		currentTrigger := claim.Spec.Generation.ReconcileTrigger

		// Сравнение: Текущий триггер в Spec отличается от последнего обработанного в Status.
		if currentTrigger != "" && currentTrigger != claim.Status.LastReconcileTrigger {
			logger.Info("ReconcileTrigger changed, starting regeneration.", "trigger", currentTrigger)
			needsSecretUpdate = true
		}
	}

	if claim.Spec.Type == "Opaque" {
		if needsUpdate(claim.Spec.Data, secret.Data) {
			logger.Info("Opaque data changed, starting secret update.")
			needsSecretUpdate = true
		}
	}

	if needsSecretUpdate {
		// Вызов функции обновления
		if err := r.updateSecret(ctx, &claim, &secret); err != nil {
			logger.Error(err, "Failed to update Secret")
			r.updateStatus(ctx, &claim, false, err.Error())
			return ctrl.Result{}, err
		}

		// Обновляем статус: сохраняем новый триггер (если AutoGenerated) и статус Synced
		// Этот метод r.updateStatus будет содержать логику сохранения LastReconcileTrigger
		r.updateStatus(ctx, &claim, true, "")
		return ctrl.Result{}, nil
	}

	return ctrl.Result{}, nil

}

func (r *SecretClaimReconciler) createSecret(ctx context.Context, claim *secretsv1alpha1.SecretClaim) error {
	secretData := make(map[string][]byte)

	switch claim.Spec.Type {
	case "Opaque":
		for k, v := range claim.Spec.Data {
			secretData[k] = []byte(v)
		}

	case "AutoGenerated":

		if claim.Spec.Generation == nil {
			return fmt.Errorf("generation spec is nil for AutoGenerated claim")
		}

		for _, key := range claim.Spec.Generation.DataKeys {
			password, err := generatePassword(claim.Spec.Generation.Length, claim.Spec.Generation.Encoding)
			if err != nil {
				return fmt.Errorf("failed to generate password: %w", err)
			}
			secretData[key] = []byte(password)
		}

	default:
		return fmt.Errorf("unknown claim type: %s", claim.Spec.Type)
	}

	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      claim.Name,
			Namespace: claim.Namespace,
		},
		Type: corev1.SecretTypeOpaque,
		Data: secretData,
	}

	if err := ctrl.SetControllerReference(claim, secret, r.Scheme); err != nil {
		return err
	}

	return r.Create(ctx, secret)
}

func (r *SecretClaimReconciler) updateSecret(ctx context.Context, claim *secretsv1alpha1.SecretClaim, existingSecret *corev1.Secret) error {
	secretData := make(map[string][]byte)

	switch claim.Spec.Type {
	case "Opaque":
		for k, v := range claim.Spec.Data {
			secretData[k] = []byte(v)
		}

	case "AutoGenerated":

		if claim.Spec.Generation == nil {
			return fmt.Errorf("generation spec is nil for AutoGenerated claim")
		}

		for _, key := range claim.Spec.Generation.DataKeys {
			password, err := generatePassword(claim.Spec.Generation.Length, claim.Spec.Generation.Encoding)
			if err != nil {
				return fmt.Errorf("failed to generate password: %w", err)
			}
			secretData[key] = []byte(password)
		}
	default:
		return fmt.Errorf("unknown claim type: %s", claim.Spec.Type)
	}

	existingSecret.Type = corev1.SecretTypeOpaque
	existingSecret.Data = secretData

	return r.Update(ctx, existingSecret)

}

func (r *SecretClaimReconciler) updateStatus(ctx context.Context, claim *secretsv1alpha1.SecretClaim, synced bool, msg string) {
	claim.Status.Synced = synced
	claim.Status.ErrorMessage = msg
	if synced {
		claim.Status.CreatedSecretName = claim.Name
		if claim.Spec.Type == "AutoGenerated" && claim.Spec.Generation != nil {
			claim.Status.LastReconcileTrigger = claim.Spec.Generation.ReconcileTrigger
		}

	}
	if err := r.Status().Update(ctx, claim); err != nil {
		fmt.Println("Failed to update status:", err)
	}
}

// SetupWithManager sets up the controller with the Manager.
func (r *SecretClaimReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&secretsv1alpha1.SecretClaim{}).
		Named("secretclaim").
		Owns(&corev1.Secret{}).
		Complete(r)
}
