// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateSecretRequestType.
const (
	CreateSecretRequestTypeAutoGenerated CreateSecretRequestType = "AutoGenerated"
	CreateSecretRequestTypeOpaque        CreateSecretRequestType = "Opaque"
)

// Defines values for GenerationConfigEncoding.
const (
	Alphanumeric GenerationConfigEncoding = "alphanumeric"
	Digits       GenerationConfigEncoding = "digits"
	Symbols      GenerationConfigEncoding = "symbols"
)

// Defines values for SecretStatusCurrentStatus.
const (
	SecretStatusCurrentStatusError    SecretStatusCurrentStatus = "Error"
	SecretStatusCurrentStatusNotFound SecretStatusCurrentStatus = "NotFound"
	SecretStatusCurrentStatusPending  SecretStatusCurrentStatus = "Pending"
	SecretStatusCurrentStatusReady    SecretStatusCurrentStatus = "Ready"
)

// Defines values for SimpleSecretStatusCurrentStatus.
const (
	SimpleSecretStatusCurrentStatusError    SimpleSecretStatusCurrentStatus = "Error"
	SimpleSecretStatusCurrentStatusNotFound SimpleSecretStatusCurrentStatus = "NotFound"
	SimpleSecretStatusCurrentStatusPending  SimpleSecretStatusCurrentStatus = "Pending"
	SimpleSecretStatusCurrentStatusReady    SimpleSecretStatusCurrentStatus = "Ready"
)

// Defines values for UpdateSecretRequestType.
const (
	UpdateSecretRequestTypeAutoGenerated UpdateSecretRequestType = "AutoGenerated"
	UpdateSecretRequestTypeOpaque        UpdateSecretRequestType = "Opaque"
)

// AuthUserRequest Login password auth
type AuthUserRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthUserResponse Response with token
type AuthUserResponse struct {
	// ExpiresIn Timeframe in seconds
	ExpiresIn *int64 `json:"expiresIn,omitempty"`

	// Token JWT-token
	Token string `json:"token"`
}

// CreateSecretRequest Create new k8s secret
type CreateSecretRequest struct {
	// Annotations Key-value pairs that are attached to the SecretClaim object
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Data Key-value data if Opaque else empty
	Data *map[string]string `json:"data,omitempty"`

	// GenerationConfig Secret generation settings
	GenerationConfig *GenerationConfig `json:"generationConfig,omitempty"`

	// Labels Key-value pairs that are attached to the SecretClaim object
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Secret name, unique for the workspace
	Name string `json:"name"`

	// Namespace Namespace name, where the secret will be created
	Namespace string `json:"namespace"`

	// Type Opaque if secret is set, AutoGenerated if the secret needs to be generated
	Type CreateSecretRequestType `json:"type"`
}

// CreateSecretRequestType Opaque if secret is set, AutoGenerated if the secret needs to be generated
type CreateSecretRequestType string

// ErrorBadRequest defines model for ErrorBadRequest.
type ErrorBadRequest struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorConflict defines model for ErrorConflict.
type ErrorConflict struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorForbidden defines model for ErrorForbidden.
type ErrorForbidden struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorInternal defines model for ErrorInternal.
type ErrorInternal struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorNotFound defines model for ErrorNotFound.
type ErrorNotFound struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// ErrorUnauthorized defines model for ErrorUnauthorized.
type ErrorUnauthorized struct {
	ErrorCode    *string `json:"errorCode,omitempty"`
	ErrorMessage *string `json:"errorMessage,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// GenerationConfig Secret generation settings
type GenerationConfig struct {
	// DataKeys List of keys to generate in the secret
	DataKeys *[]string `json:"dataKeys,omitempty"`

	// Encoding password type
	Encoding *GenerationConfigEncoding `json:"encoding,omitempty"`

	// Length Generated secret len
	Length int32 `json:"length"`
}

// GenerationConfigEncoding password type
type GenerationConfigEncoding string

// ListSecretsResponse All SecretClaims in the Namespace
type ListSecretsResponse struct {
	Items []SecretSummary `json:"items"`
}

// OkResponse defines model for OkResponse.
type OkResponse struct {
	Ok *bool `json:"ok,omitempty"`
}

// SecretResponse Response of a k8s secret resources
type SecretResponse struct {
	// Annotations Key-value pairs that are attached to the SecretClaim object
	Annotations *map[string]string `json:"annotations,omitempty"`

	// CreationTimestamp The timestamp when the SecretClaim object was created
	CreationTimestamp *time.Time `json:"creationTimestamp,omitempty"`

	// Data Key-value data of the *actual* Kubernetes Secret. Only returned if Synced is true
	Data *map[string]string `json:"data,omitempty"`

	// GenerationConfig Secret generation settings
	GenerationConfig *GenerationConfig `json:"generationConfig,omitempty"`

	// Labels Key-value pairs that are attached to the SecretClaim object
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Secret name
	Name string `json:"name"`

	// Namespace Namespace name
	Namespace *string `json:"namespace,omitempty"`

	// ResourceVersion Internal version of this object
	ResourceVersion *string      `json:"resourceVersion,omitempty"`
	Status          SecretStatus `json:"status"`

	// Type Opaque or AutoGenerated
	Type string `json:"type"`

	// Uid Unique ID of the SecretClaim object
	Uid *string `json:"uid,omitempty"`
}

// SecretStatus defines model for SecretStatus.
type SecretStatus struct {
	// CurrentStatus High-level status determined by the operator (Pending, Ready, Error, NotFound)
	CurrentStatus SecretStatusCurrentStatus `json:"currentStatus"`

	// ErrorMessage Detailed error message from the operator if currentStatus is Error
	ErrorMessage *string `json:"errorMessage,omitempty"`

	// LastSyncTime The timestamp of the last successful synchronization
	LastSyncTime *time.Time `json:"lastSyncTime,omitempty"`

	// SecretName The name of the actual Kubernetes Secret created by the operator
	SecretName *string `json:"secretName,omitempty"`

	// Synced True if the actual Kubernetes Secret has been successfully created and synchronized
	Synced bool `json:"synced"`
}

// SecretStatusCurrentStatus High-level status determined by the operator (Pending, Ready, Error, NotFound)
type SecretStatusCurrentStatus string

// SecretSummary Summarized version of a SecretClaim for list views
type SecretSummary struct {
	// CreationTimestamp The timestamp when the SecretClaim object was created
	CreationTimestamp *time.Time `json:"creationTimestamp,omitempty"`

	// Name Secret name
	Name string `json:"name"`

	// Namespace Namespace name
	Namespace *string            `json:"namespace,omitempty"`
	Status    SimpleSecretStatus `json:"status"`

	// Type Opaque or AutoGenerated
	Type string `json:"type"`
}

// SimpleSecretStatus defines model for SimpleSecretStatus.
type SimpleSecretStatus struct {
	// CurrentStatus High-level status determined by the operator
	CurrentStatus SimpleSecretStatusCurrentStatus `json:"currentStatus"`

	// Synced True if the actual Kubernetes Secret has been successfully created
	Synced *bool `json:"synced,omitempty"`
}

// SimpleSecretStatusCurrentStatus High-level status determined by the operator
type SimpleSecretStatusCurrentStatus string

// UpdateSecretRequest Request body to update the data of an existing Secret
type UpdateSecretRequest struct {
	// Annotations New set of key-value annotations to overwrite existing annotations. Pass empty object to clear
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Data New key-value data if type='Opaque'. Pass empty object to clear
	Data *map[string]string `json:"data,omitempty"`

	// GenerationConfig Secret generation settings
	GenerationConfig *GenerationConfig `json:"generationConfig,omitempty"`

	// Labels New set of key-value labels to overwrite existing labels. Pass empty object to clear
	Labels *map[string]string `json:"labels,omitempty"`

	// Regenerate Value to regenerate value in update request. Only if 'AutoGenerated'
	Regenerate *bool `json:"regenerate,omitempty"`

	// Type Pass to change the secret type
	Type *UpdateSecretRequestType `json:"type,omitempty"`
}

// UpdateSecretRequestType Pass to change the secret type
type UpdateSecretRequestType string

// Namespace defines model for Namespace.
type Namespace = string

// ResourceName defines model for ResourceName.
type ResourceName = string

// XRequestID defines model for XRequestID.
type XRequestID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorBadRequest

// Conflict defines model for Conflict.
type Conflict = ErrorConflict

// Forbidden defines model for Forbidden.
type Forbidden = ErrorForbidden

// Internal defines model for Internal.
type Internal = ErrorInternal

// NotFound defines model for NotFound.
type NotFound = ErrorNotFound

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorUnauthorized

// ListSecretsParams defines parameters for ListSecrets.
type ListSecretsParams struct {
	Namespace Namespace `form:"namespace" json:"namespace"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// CreateSecretParams defines parameters for CreateSecret.
type CreateSecretParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// DeleteSecretParams defines parameters for DeleteSecret.
type DeleteSecretParams struct {
	Namespace Namespace `form:"namespace" json:"namespace"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// GetSecretParams defines parameters for GetSecret.
type GetSecretParams struct {
	Namespace Namespace `form:"namespace" json:"namespace"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// UpdateSecretParams defines parameters for UpdateSecret.
type UpdateSecretParams struct {
	Namespace Namespace `form:"namespace" json:"namespace"`

	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// AuthUserParams defines parameters for AuthUser.
type AuthUserParams struct {
	// XRequestID Correlation ID for tracing
	XRequestID *XRequestID `json:"X-Request-ID,omitempty"`
}

// CreateSecretJSONRequestBody defines body for CreateSecret for application/json ContentType.
type CreateSecretJSONRequestBody = CreateSecretRequest

// UpdateSecretJSONRequestBody defines body for UpdateSecret for application/json ContentType.
type UpdateSecretJSONRequestBody = UpdateSecretRequest

// AuthUserJSONRequestBody defines body for AuthUser for application/json ContentType.
type AuthUserJSONRequestBody = AuthUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List available secrets
	// (GET /secrets)
	ListSecrets(w http.ResponseWriter, r *http.Request, params ListSecretsParams)
	// Create a secret
	// (POST /secrets)
	CreateSecret(w http.ResponseWriter, r *http.Request, params CreateSecretParams)
	// Delete secret
	// (DELETE /secrets/{name})
	DeleteSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params DeleteSecretParams)
	// Get secret from vault
	// (GET /secrets/{name})
	GetSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params GetSecretParams)
	// Update secret
	// (PUT /secrets/{name})
	UpdateSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params UpdateSecretParams)
	// Exchange Auth Data for JWT
	// (POST /user/auth)
	AuthUser(w http.ResponseWriter, r *http.Request, params AuthUserParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List available secrets
// (GET /secrets)
func (_ Unimplemented) ListSecrets(w http.ResponseWriter, r *http.Request, params ListSecretsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a secret
// (POST /secrets)
func (_ Unimplemented) CreateSecret(w http.ResponseWriter, r *http.Request, params CreateSecretParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete secret
// (DELETE /secrets/{name})
func (_ Unimplemented) DeleteSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params DeleteSecretParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get secret from vault
// (GET /secrets/{name})
func (_ Unimplemented) GetSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params GetSecretParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update secret
// (PUT /secrets/{name})
func (_ Unimplemented) UpdateSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params UpdateSecretParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange Auth Data for JWT
// (POST /user/auth)
func (_ Unimplemented) AuthUser(w http.ResponseWriter, r *http.Request, params AuthUserParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSecrets operation middleware
func (siw *ServerInterfaceWrapper) ListSecrets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSecretsParams

	// ------------- Required query parameter "namespace" -------------

	if paramValue := r.URL.Query().Get("namespace"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "namespace"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSecrets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSecret operation middleware
func (siw *ServerInterfaceWrapper) CreateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSecretParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSecret(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSecret operation middleware
func (siw *ServerInterfaceWrapper) DeleteSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ResourceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteSecretParams

	// ------------- Required query parameter "namespace" -------------

	if paramValue := r.URL.Query().Get("namespace"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "namespace"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSecret(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSecret operation middleware
func (siw *ServerInterfaceWrapper) GetSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ResourceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSecretParams

	// ------------- Required query parameter "namespace" -------------

	if paramValue := r.URL.Query().Get("namespace"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "namespace"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSecret(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSecret operation middleware
func (siw *ServerInterfaceWrapper) UpdateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name ResourceName

	err = runtime.BindStyledParameterWithOptions("simple", "name", chi.URLParam(r, "name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateSecretParams

	// ------------- Required query parameter "namespace" -------------

	if paramValue := r.URL.Query().Get("namespace"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "namespace"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSecret(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthUser operation middleware
func (siw *ServerInterfaceWrapper) AuthUser(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthUserParams

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthUser(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/secrets", wrapper.ListSecrets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/secrets", wrapper.CreateSecret)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/secrets/{name}", wrapper.DeleteSecret)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/secrets/{name}", wrapper.GetSecret)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/secrets/{name}", wrapper.UpdateSecret)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/user/auth", wrapper.AuthUser)
	})

	return r
}

type BadRequestJSONResponse ErrorBadRequest

type ConflictJSONResponse ErrorConflict

type ForbiddenJSONResponse ErrorForbidden

type InternalJSONResponse ErrorInternal

type NotFoundJSONResponse ErrorNotFound

type OkResponseJSONResponse OkResponse

type UnauthorizedJSONResponse ErrorUnauthorized

type ListSecretsRequestObject struct {
	Params ListSecretsParams
}

type ListSecretsResponseObject interface {
	VisitListSecretsResponse(w http.ResponseWriter) error
}

type ListSecrets200JSONResponse ListSecretsResponse

func (response ListSecrets200JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSecrets400JSONResponse struct{ BadRequestJSONResponse }

func (response ListSecrets400JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListSecrets401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSecrets401JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListSecrets403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListSecrets403JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListSecrets404JSONResponse struct{ NotFoundJSONResponse }

func (response ListSecrets404JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListSecrets500JSONResponse struct{ InternalJSONResponse }

func (response ListSecrets500JSONResponse) VisitListSecretsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecretRequestObject struct {
	Params CreateSecretParams
	Body   *CreateSecretJSONRequestBody
}

type CreateSecretResponseObject interface {
	VisitCreateSecretResponse(w http.ResponseWriter) error
}

type CreateSecret201JSONResponse struct{ OkResponseJSONResponse }

func (response CreateSecret201JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecret400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSecret400JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecret401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSecret401JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecret403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateSecret403JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecret404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateSecret404JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecret409JSONResponse struct{ ConflictJSONResponse }

func (response CreateSecret409JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateSecret500JSONResponse struct{ InternalJSONResponse }

func (response CreateSecret500JSONResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSecretRequestObject struct {
	Name   ResourceName `json:"name"`
	Params DeleteSecretParams
}

type DeleteSecretResponseObject interface {
	VisitDeleteSecretResponse(w http.ResponseWriter) error
}

type DeleteSecret200JSONResponse struct{ OkResponseJSONResponse }

func (response DeleteSecret200JSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSecret400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteSecret400JSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSecret401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteSecret401JSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSecret403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteSecret403JSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSecret404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSecret404JSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSecret500JSONResponse struct{ InternalJSONResponse }

func (response DeleteSecret500JSONResponse) VisitDeleteSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSecretRequestObject struct {
	Name   ResourceName `json:"name"`
	Params GetSecretParams
}

type GetSecretResponseObject interface {
	VisitGetSecretResponse(w http.ResponseWriter) error
}

type GetSecret200JSONResponse SecretResponse

func (response GetSecret200JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSecret400JSONResponse struct{ BadRequestJSONResponse }

func (response GetSecret400JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSecret401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSecret401JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSecret403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetSecret403JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSecret404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSecret404JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSecret500JSONResponse struct{ InternalJSONResponse }

func (response GetSecret500JSONResponse) VisitGetSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSecretRequestObject struct {
	Name   ResourceName `json:"name"`
	Params UpdateSecretParams
	Body   *UpdateSecretJSONRequestBody
}

type UpdateSecretResponseObject interface {
	VisitUpdateSecretResponse(w http.ResponseWriter) error
}

type UpdateSecret200JSONResponse struct{ OkResponseJSONResponse }

func (response UpdateSecret200JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSecret400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSecret400JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSecret401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateSecret401JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSecret403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateSecret403JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSecret404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSecret404JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSecret500JSONResponse struct{ InternalJSONResponse }

func (response UpdateSecret500JSONResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthUserRequestObject struct {
	Params AuthUserParams
	Body   *AuthUserJSONRequestBody
}

type AuthUserResponseObject interface {
	VisitAuthUserResponse(w http.ResponseWriter) error
}

type AuthUser200JSONResponse AuthUserResponse

func (response AuthUser200JSONResponse) VisitAuthUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthUser400JSONResponse struct{ BadRequestJSONResponse }

func (response AuthUser400JSONResponse) VisitAuthUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AuthUser401JSONResponse) VisitAuthUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthUser500JSONResponse struct{ InternalJSONResponse }

func (response AuthUser500JSONResponse) VisitAuthUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List available secrets
	// (GET /secrets)
	ListSecrets(ctx context.Context, request ListSecretsRequestObject) (ListSecretsResponseObject, error)
	// Create a secret
	// (POST /secrets)
	CreateSecret(ctx context.Context, request CreateSecretRequestObject) (CreateSecretResponseObject, error)
	// Delete secret
	// (DELETE /secrets/{name})
	DeleteSecret(ctx context.Context, request DeleteSecretRequestObject) (DeleteSecretResponseObject, error)
	// Get secret from vault
	// (GET /secrets/{name})
	GetSecret(ctx context.Context, request GetSecretRequestObject) (GetSecretResponseObject, error)
	// Update secret
	// (PUT /secrets/{name})
	UpdateSecret(ctx context.Context, request UpdateSecretRequestObject) (UpdateSecretResponseObject, error)
	// Exchange Auth Data for JWT
	// (POST /user/auth)
	AuthUser(ctx context.Context, request AuthUserRequestObject) (AuthUserResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListSecrets operation middleware
func (sh *strictHandler) ListSecrets(w http.ResponseWriter, r *http.Request, params ListSecretsParams) {
	var request ListSecretsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSecrets(ctx, request.(ListSecretsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSecrets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSecretsResponseObject); ok {
		if err := validResponse.VisitListSecretsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSecret operation middleware
func (sh *strictHandler) CreateSecret(w http.ResponseWriter, r *http.Request, params CreateSecretParams) {
	var request CreateSecretRequestObject

	request.Params = params

	var body CreateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSecret(ctx, request.(CreateSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSecretResponseObject); ok {
		if err := validResponse.VisitCreateSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSecret operation middleware
func (sh *strictHandler) DeleteSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params DeleteSecretParams) {
	var request DeleteSecretRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSecret(ctx, request.(DeleteSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSecretResponseObject); ok {
		if err := validResponse.VisitDeleteSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSecret operation middleware
func (sh *strictHandler) GetSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params GetSecretParams) {
	var request GetSecretRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSecret(ctx, request.(GetSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSecretResponseObject); ok {
		if err := validResponse.VisitGetSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSecret operation middleware
func (sh *strictHandler) UpdateSecret(w http.ResponseWriter, r *http.Request, name ResourceName, params UpdateSecretParams) {
	var request UpdateSecretRequestObject

	request.Name = name
	request.Params = params

	var body UpdateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSecret(ctx, request.(UpdateSecretRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSecret")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSecretResponseObject); ok {
		if err := validResponse.VisitUpdateSecretResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthUser operation middleware
func (sh *strictHandler) AuthUser(w http.ResponseWriter, r *http.Request, params AuthUserParams) {
	var request AuthUserRequestObject

	request.Params = params

	var body AuthUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthUser(ctx, request.(AuthUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthUserResponseObject); ok {
		if err := validResponse.VisitAuthUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
