package handlers

import (
	"context"

	"github.com/mogilyoy/k8s-secret-manager/internal/api"
	"github.com/mogilyoy/k8s-secret-manager/internal/auth"
)

func (h *SecretHandler) CreateSecret(ctx context.Context, request api.CreateSecretRequestObject) (api.CreateSecretResponseObject, error) {
	claims, err := auth.GetClaimsFromContext(ctx)
	if err != nil {
		return BuildCreateSecretErrorResponse(ErrorResult{
			ErrorMessage: "Cannot parse request context",
			ErrorCode:    "InternalServerError",
			StatusCode:   500,
		}), nil
	}

	if !auth.IsNamespaceAllowed(*request.Body.Namespace, claims.AllowedNamespaces) || claims.Role == "developer" {
		return BuildCreateSecretErrorResponse(ErrorResult{
			ErrorMessage: "Access denied: insufficient role or namespace permissions",
			ErrorCode:    "Forbidden",
			StatusCode:   403,
		}), nil
	}

	if (request.Body.Type != "AutoGenerated" && (request.Body.Data == nil || request.Body.GenerationConfig != nil)) ||
		(request.Body.Type == "AutoGenerated" && (request.Body.GenerationConfig == nil || request.Body.Data != nil)) {
		return BuildCreateSecretErrorResponse(ErrorResult{
			ErrorMessage: "Wrong response format",
			ErrorCode:    "BadRequest",
			StatusCode:   400,
		}), nil
	}

	err = h.K8sManager.CreateSecretClaim(ctx, request.Body.Name, *request.Body.Namespace, string(request.Body.Type), *request.Body.Data)
	if err != nil {
		return BuildCreateSecretErrorResponse(HandleK8sError(err)), nil
	}

	return api.CreateSecret201JSONResponse{
		OkResponseJSONResponse: api.OkResponseJSONResponse{
			Ok: BoolPnc(true),
		},
	}, nil
}

func (h *SecretHandler) ListSecrets(ctx context.Context, request api.ListSecretsRequestObject) (api.ListSecretsResponseObject, error) {
	claims, err := auth.GetClaimsFromContext(ctx)
	if err != nil {
		return BuildListSecretsErrorResponse(ErrorResult{
			ErrorMessage: "Cannot parse request context",
			ErrorCode:    "InternalServerError",
			StatusCode:   500,
		}), nil
	}
	if !auth.IsNamespaceAllowed(request.Params.Namespace, claims.AllowedNamespaces) {
		return BuildListSecretsErrorResponse(ErrorResult{
			ErrorMessage: "Access denied: insufficient role or namespace permissions",
			ErrorCode:    "Forbidden",
			StatusCode:   403,
		}), nil
	}

	secretClaimList, err := h.K8sManager.ListSecretClaim(ctx, request.Params.Namespace)
	if err != nil {
		return BuildListSecretsErrorResponse(HandleK8sError(err)), nil
	}

	secretResponses := make([]api.SecretResponse, 0, len(secretClaimList.Items))

	for _, claim := range secretClaimList.Items {
		response := mapClaimToSecretResponse(&claim, nil)
		secretResponses = append(secretResponses, response)
	}

	return api.ListSecrets200JSONResponse{
		Items: secretResponses,
	}, nil
}

func (h *SecretHandler) GetSecret(ctx context.Context, request api.GetSecretRequestObject) (api.GetSecretResponseObject, error) {
	claims, err := auth.GetClaimsFromContext(ctx)
	if err != nil {
		return BuildGetSecretErrorResponse(ErrorResult{
			ErrorMessage: "Cannot parse request context",
			ErrorCode:    "InternalServerError",
			StatusCode:   500,
		}), nil
	}

	if !auth.IsNamespaceAllowed(request.Params.Namespace, claims.AllowedNamespaces) {
		return BuildGetSecretErrorResponse(ErrorResult{
			ErrorMessage: "Access denied: insufficient role or namespace permissions",
			ErrorCode:    "Forbidden",
			StatusCode:   403,
		}), nil
	}

	secret, err := h.K8sManager.GetSecretClaim(ctx, request.Name, request.Params.Namespace)

	if err != nil {
		return BuildGetSecretErrorResponse(HandleK8sError(err)), nil
	}

	var actualData map[string]string = nil
	if secret.Status.Synced {

		actualData, err = h.K8sManager.GetActualSecretData(ctx, request.Name, request.Params.Namespace)
		if err != nil {
			return BuildGetSecretErrorResponse(HandleK8sError(err)), nil
		}
	}

	if actualData == nil && secret.Spec.Type == "Opaque" {
		actualData = secret.Spec.Data
	}

	secretResponse := mapClaimToSecretResponse(secret, actualData)

	return api.GetSecret200JSONResponse(secretResponse), nil
}

func (h *SecretHandler) UpdateSecret(ctx context.Context, request api.UpdateSecretRequestObject) (api.UpdateSecretResponseObject, error) {
	claims, err := auth.GetClaimsFromContext(ctx)
	if err != nil {
		return BuildUpdateSecretErrorResponse(ErrorResult{
			ErrorMessage: "Cannot parse request context",
			ErrorCode:    "InternalServerError",
			StatusCode:   500,
		}), nil
	}

	if !auth.IsNamespaceAllowed(request.Params.Namespace, claims.AllowedNamespaces) || claims.Role == "developer" {
		return BuildUpdateSecretErrorResponse(ErrorResult{
			ErrorMessage: "Access denied: insufficient role or namespace permissions",
			ErrorCode:    "Forbidden",
			StatusCode:   403,
		}), nil
	}

	var newType string
	if request.Body.Type != nil {
		newType = string(*request.Body.Type)
	}

	regenerate := false
	if request.Body.Regenerate != nil {
		regenerate = *request.Body.Regenerate
	}

	var newData map[string]string
	if request.Body.Data != nil {
		newData = *request.Body.Data
	}

	updatedSecret, err := h.K8sManager.UpdateSecretClaim(ctx, request.Name, request.Params.Namespace, newType, regenerate, newData)
	if err != nil {
		return BuildUpdateSecretErrorResponse(HandleK8sError(err)), nil
	}

	secretResponse := mapClaimToSecretResponse(updatedSecret, nil)

	return api.UpdateSecret200JSONResponse(secretResponse), nil
}

func (h *SecretHandler) DeleteSecret(ctx context.Context, request api.DeleteSecretRequestObject) (api.DeleteSecretResponseObject, error) {
	claims, err := auth.GetClaimsFromContext(ctx)
	if err != nil {
		return BuildDeleteSecretErrorResponse(ErrorResult{
			ErrorMessage: "Cannot parse request context",
			ErrorCode:    "InternalServerError",
			StatusCode:   500,
		}), nil
	}

	if !auth.IsNamespaceAllowed(request.Params.Namespace, claims.AllowedNamespaces) || claims.Role == "developer" {
		return BuildDeleteSecretErrorResponse(ErrorResult{
			ErrorMessage: "Access denied: insufficient role or namespace permissions",
			ErrorCode:    "Forbidden",
			StatusCode:   403,
		}), nil
	}

	err = h.K8sManager.DeleteSecretClaim(ctx, request.Name, request.Params.Namespace)
	if err != nil {
		return BuildDeleteSecretErrorResponse(HandleK8sError(err)), nil
	}

	return api.DeleteSecret200JSONResponse{
		OkResponseJSONResponse: api.OkResponseJSONResponse{
			Ok: BoolPnc(true),
		},
	}, nil

}
